import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import Navbar from '@/app/Navbar/navbar'
// import { GlobalContextProvider } from './Context/navcontext';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>

        {/* <GlobalContextProvider> */}

          <Navbar />
          {children}
        {/* </GlobalContextProvider> */}

      </body>
    </html>
  )
}
